### ISSUE TITLE
Multi-file upload: All files are uploaded to same folder (subfolders are not created)

### ISSUE THREAD

**Issue by fohrloop** [np-8/dash-uploader#76]
As the title says, when using multi-file upload functionality, all the uploaded files are uploaded into same folder. The uploader does not create subfolders.

- Affected dash-uploader version: 0.7.0dev 279ee87

### Todo
- [ ] Check if this can be fixed on Chrome
- [ ] Check if this can be fixed on other browsers
    - [ ] If not, check if an alert could be shown to users with unsupported browsers

**Comment by yigitsoy** [comment]
This also affects the case if there are files at different hierarchy levels having the same name+ext. 

```
- file.txt
- folder\
  - file.txt

```
The current version simply overwrites the previously uploaded file.

**Comment by fohrloop** [comment]
Yeah that's a good point.
